apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: p7
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data
  namespace: p7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi